services:
  github-runner:
    image: myoung34/docker-github-actions-runner:latest
    restart: always
    environment:
      REPO_URL: https://github.com/ravilushqa/homelab
      RUNNER_NAME: komodo-runner
      RUNNER_TOKEN: "${RUNNER_TOKEN}"
      RUNNER_WORKDIR: /tmp/runner/work
      LABELS: self-hosted,linux,x64,homelab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-work:/tmp/runner/work

volumes:
  runner-work:
