services:
  github-runner:
    image: myoung34/github-runner:ubuntu-noble
    restart: always
    environment:
      REPO_URL: https://github.com/ravilushqa/homelab
      RUNNER_NAME: komodo-runner
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      RUNNER_WORKDIR: /tmp/runner/work
      LABELS: self-hosted,linux,x64,homelab
      EPHEMERAL: "true"
      DISABLE_AUTO_UPDATE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
