services:
  github-runner:
    image: myoung34/github-runner:latest
    restart: always
    environment:
      REPO_URL: https://github.com/ravilushqa/homelab
      RUNNER_NAME: komodo-runner
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      RUNNER_WORKDIR: /tmp/runner/work
      LABELS: self-hosted,linux,x64,homelab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-work:/tmp/runner/work

volumes:
  runner-work:
