services:
  rsshub:
    image: diygod/rsshub:latest
    container_name: rsshub
    restart: unless-stopped
    ports:
      - 1200:1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: memory
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rsshub.rule=Host(`rsshub.ravil.space`)"
      - "traefik.http.routers.rsshub.entrypoints=websecure"
      - "traefik.http.routers.rsshub.tls.certresolver=cloudflare"
      - "traefik.http.services.rsshub.loadbalancer.server.port=1200"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.rsshub.middlewares=oidc-auth@docker,umami@docker"

networks:
  default:
    name: rsshub_default
  traefik:
    name: traefik_default
    external: true
