services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command: serve
    environment:
      - TZ=Europe/Berlin
      - NTFY_BASE_URL=https://ntfy.ravil.space
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-auth:/var/lib/ntfy
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.ntfy.rule=Host(`ntfy.ravil.space`)
      - traefik.http.routers.ntfy.entrypoints=websecure
      - traefik.http.routers.ntfy.tls.certresolver=cloudflare
      - traefik.http.services.ntfy.loadbalancer.server.port=80

volumes:
  ntfy-cache:
  ntfy-auth:

networks:
  traefik_default:
    external: true
