services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: ${N8N_DB_HOST}
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_USER: ravilushqa
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD}
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "false"
      DB_POSTGRESDB_SSL_MODE: require
      N8N_HOST: n8n.ravil.space
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://n8n.ravil.space
      GENERIC_TIMEZONE: Europe/Berlin
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.ravil.space`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=cloudflare"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=traefik_default"

volumes:
  n8n_data:

networks:
  default:
    name: n8n_default
  traefik:
    name: traefik_default
    external: true
